version: 2
updates:
- package-ecosystem: nuget
  directory: /src/MiniRPG.Tests/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
  groups:
    core:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: nuget
  directory: /src/MiniRPG/
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
  groups:
    core:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  assignees:
  - samsmithnz
  open-pull-requests-limit: 10
  groups:
    actions:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
