name: .NET CI/CD
on:
  push:
    branches:
    - main
    paths-ignore:
    - 'MiniRPGGame/**'
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'MiniRPGGame/**'
jobs:
  build:
    name: Build job
    runs-on: windows-latest
    outputs:
      Version: ${{ steps.gitversion.outputs.MajorMinorPatch }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v4.0.1
      with:
        versionSpec: 6.x
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4.0.1
    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ steps.gitversion.outputs.MajorMinorPatch }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: .NET test
      run: dotnet test src/MiniRPG.Tests/MiniRPG.Tests.csproj -c Debug
    - name: .NET publish
      run: dotnet publish src/MiniRPG.Logic/MiniRPG.Logic.csproj -c Debug -p:Version='${{ steps.gitversion.outputs.MajorMinorPatch }}'
    - name: Copy MiniRPG output to Assets/Logic
      if: false
      run: xcopy /s /e /y src/MiniRPG.Logic/bin/Debug MiniRPGGame/Assets/Logic/
    - name: Upload package back to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: src/MiniRPG/bin/Release
